### PR TITLE
Allow for passing in an existing HTTP server

### PR DESCRIPTION
**Pull request by inxilpro**
Implements https://github.com/deepstreamIO/deepstream.io/issues/87 and the server component of https://github.com/deepstreamIO/deepstream.io-client-js/issues/63

### CODE REVIEW

**Comment by yasserf** [comment]
Nice!

Could you add tests in:

https://github.com/deepstreamIO/deepstream.io/blob/master/test/message/connection-endpointSpec.js

So that we know the passed in server has listen called on it? We already have a mockHttpServer so it should make things alot easier.

 https://github.com/deepstreamIO/deepstream.io/blob/master/test/message/connection-endpointSpec.js#L4

**Comment by yasserf** [comment]
@WolframHempe @inxilpro l Should we have config sanity checks? There are a few option combinations now for creating a server.. if someone passes in the ssl cert and a httpserver it means something has been configured wrong

**Comment by yasserf** [comment]
deepstreamIO/deepstream.io-client-js#63 would still require the functionality to no longer provide a url when being created and instead piggy back the pages root url + the url path configured

**Comment by inxilpro** [comment]
@yasserf Just added some tests. The connection endpoint doesn't directly call `listen()`, but I added tests to make sure `_checkReady()` gets called regardless of whether `listen()` is called *before* or *after* the server is passed to deepstream.

That means both of these should work:

```javascript
// Listen second
var server = http.createServer();
deepstream.set('httpServer', server);
server.listen(6020);

// Listen first
var server = http.createServer();
server.listen(6020);
deepstream.set('httpServer', server);
```

**Comment by yasserf** [comment]
Awesome thanks!

We just fixed #94 as well, so there are going to be a couple of merge conflicts unfortunately, but we'll merge your stuff in and sort that out as part of the merge.

**Comment by CLClark** [comment]
this was deprecated... right?

**Comment by yasserf** [comment]
Yup, was removed in V2

**Pull request merged**
