### PR TITLE
provide eslint and npm lint script

### PR DESCRIPTION
**Pull request by timaschew**

### CODE REVIEW

**Comment by yasserf** [comment]
Awesome!

**Comment by yasserf** [comment]
```
> deepstream.io@1.0.0-beta.3 lint-quiet /home/travis/build/deepstreamIO/deepstream.io
> eslint . --no-color -o coverage/lint-result.log || true && tail -n 3 coverage/lint-result.log
  158:3   error    There must be a space inside this paren  space-in-parens
✖ 7527 problems (6652 errors, 875 warnings)
```

Guessing were not going to get the build to pass anytime soon! =P

**Comment by timaschew** [comment]
This is the reason why I added `|| true` to the end of the script, it won't break the build.

So next steps could be:

1. verify that the lint rules are okay for our current codebase
2. run `eslint . --fix` the result then is _only_ 5018 problems (4143 errors, 875 warnings)
3. at the end move on iteratively, for instance: if you edit a file in the context of another feature/bugfix, then try to fix the lint errors.

BTW:
I only get 6644 problems (5769 errors, 875 warnings) 
Not sure in which branch you executed it?

**Comment by yasserf** [comment]
Copied it from travis, didn't try it locally yet tbh.

**Comment by yasserf** [comment]
Closing for now, but lets keep branch for post 1.0 release

**Pull request closed without merging**
