### PR TITLE
Auto Dependency Updates ...

### PR DESCRIPTION
**Pull request by lguzzon**

### CODE REVIEW

**Comment by yasserf** [comment]
Hey,  thank you for the update. Unfortunately upgrading async breaks the license generator. Bcc can you revert out to 0.x and the build should go green, thanks!

**Comment by yasserf** [comment]
Awesome, thanks!

I know this isn't a code commit, but we have a policy for our [CLA](https://deepstream.io/info/community/cla/) to be signed before we can merge anything into deepstream.io

Would you be okay with signing?

**Comment by lguzzon** [comment]
Signed!!!
Is that enought?
Bye

**Comment by yasserf** [comment]
Perfect, thanks you

**Pull request merged**
