### PR TITLE
Ensure ./dist is the single source of assets

### PR DESCRIPTION
**Pull request by clintwood**
This PR does 4 things:

1) Ensures that any `import` or asset paths in the code do not reach out of the `./dist` folder.
2) Ensures that the build copies all files needed to run exclusively from `./dist` folder.
3) Fixes a tiny error/warning where `requestHeaders` variable may be null.
4) Removes `./dist` folder from the repo - it is entirely destroyed and rebuilt during any project build step and therefore adds unnecessary changes (e.g. *.map file changes) into the repo.

Please note this PR is a little opinionated in terms removing the `./dist` from the repo so please feel free to close if this is not inline with the repo's objectives.  This PR is actually a precursor to another PR which I may push in respect of an issue which was highlighted from an async `storage` plugin I have developed...

Lastly, this project is massively helpful and greatly appreciated!

### CODE REVIEW

**Comment by yasserf** [comment]
I'm totally for this, have a huge dislike for checking in built files.

Two small problems though:
1- Need to make sure we can build the binary and it loads correctly 
2- How do we deal with people running off of master builds?

If we can tackle those I will totally merge this in! And thank you!

**Comment by clintwood** [comment]
@yasserf, why I did this is because I have a custom docker build script that does the following (off of this merge branch and given that `npm i` has been run on this branch I do):
1) `npm run tsc` to build/compile to `./dist`
2) copy `./dist` to my own docker `<docker-build-context>/build` folder
3) within the Dockerfile do:
  a) `COPY ./build .`
  b) `RUN npm i --production`  

I'm not seeing any issues doing it this way but I think you referring to your build/packaging/release process which I haven't looked into!  If I have a moment I will do that and take a look at running off master builds too!

**Comment by clintwood** [comment]
I've added `./scripts/merge-pkgs.js` which is used to copy & modify `./package.json` to `./dist/package.json` updating paths to point directly into `./dist`. Also added npm run script `copy-pkg` which uses this script and lastly modified npm run script `tsc` to use `copy-pkg`.

From my limited testing if you copy `./dist` to another location and do `npm i` followed by `npm run start` it works 100% (for me)!

**Comment by jdmnd** [comment]
Hey @clintwood.
I'm looking at getting this merged. Would you mind signing our [Contributor License Agreement](https://deepstream.typeform.com/to/PwwNd5)?

**Comment by clintwood** [comment]
Hey @jdmnd, have signed!

**Comment by yasserf** [comment]
Will need to test this out before installing.

Generally, if dist is not generated wouldn't that require typescript to be installed when cloning and installing from master?

**Comment by clintwood** [comment]
Assuming you have run `npm i` on the repo and then `npm run tsc` from what I can see `./dist` is already compiled (i.e. it is a bunch on .js and .js.map files).  So unless you require compiling at runtime for some reason (plugins?), no I don't see that you need typescript at all.

My current build workflow is to run `npm run tsc` as above then literally copy `./dist` to a completely separate (docker) folder, change some config stuff (and file perms on `./bin/deepstream`) and go `./bin/deepstream` and it runs without error.

**Comment by yasserf** [comment]
Very sorry, but closing this due to conflicts and trying to get 4.0 out with any big changes. Thank you for raising though!

**Pull request closed without merging**
