### PR TITLE
Listening bug

### PR DESCRIPTION
**Pull request by yasserf**
@ronag @jdmnd

### CODE REVIEW

**Comment by ronag** [comment]
I'm not much help here. The listening part is unfortunately the only code that I don't understand in deepstream...

**Comment by yasserf** [comment]
Are you okay with the decision I made and stated in the issue regarding unsubscribing the client from the server?

**Comment by yasserf** [comment]
Should also make a note to draw a nice big complicate state diagram for listening lol

**Comment by ronag** [comment]
> Are you okay with the decision I made and stated in the issue regarding unsubscribing the client from the server?

I don't know. Maybe I'm to tired right now. I'll try to think about it again next week.

**Comment by ronag** [comment]
This PR seems to lead to lots of weird `NOT_SUBSCRIBED` errors... debugging...

**Comment by ronag** [comment]
Yep, doesn't happen after reverting...

**Comment by ronag** [comment]
@yasserf: What can I do to help with this?

**Comment by yasserf** [comment]
Will need to investigate further, are you discarding again on your app?

**Comment by yasserf** [comment]
A solution is to discard records your providing when subscription of lost, just gets duplicated easy in application logic

**Comment by ronag** [comment]
@yasserf: Sorry... I didn't understand any of that? No my app only discards once, I've got invariants making sure of that. If it did it twice I would have had the error even without this PR, no?

**Comment by yasserf** [comment]
Closing due to issues.

> @yasserf: Sorry... I didn't understand any of that? No my app only discards once, I've got invariants making sure of that. If it did it twice I would have had the error even without this PR, no?

What I meant is that since the server discards it in this PR your discard would be considered unsolicited.

**Comment by ronag** [comment]
> What I meant is that since the server discards it in this PR your discard would be considered unsolicited.

Ah, now I understand... maybe that's fine... but it's a bit weird and does feel a bit like a workaround/hack...

**Pull request closed without merging**
