### PR TITLE
Listen records in server which you received from clients

### PR DESCRIPTION
**Pull request by Chinafreak**
With this function you're abled to get all records which you receive from clients. This is very important for debug stuffs so you can check if all data of this record look fine.

Of course you can filter those records with pattern/regex which it's already build-in. Feel free to improve it. I just added it because I needed it.

### CODE REVIEW

**Comment by Chinafreak** [comment]
need a better solution than checking every 1ms at setInterval to receive records data

**Comment by Chinafreak** [comment]
Travis CI make problem. It's not my fault anymore. (Time limit reached)

**Comment by yasserf** [comment]
Hey @Chinafreak 

Many thanks for raising. Unfortunately we won't be able to merge this in, since deepstream is required to run a standalone binary as well as due to to performance issues.

You may be able to create this is a plugin by capturing the data when it enters deepstream via the permission hook btw, would mean you don't need to maintain your own fork if your don't want!

Thanks again!

**Comment by Chinafreak** [comment]
But how about you can enable/disable this settings? If the server runs on standalone, disable this function. If the server runs on node.js or something like that, enable debug modus? Then the performance issues should not be a problem anymore.

**Comment by Chinafreak** [comment]
any update?

**Pull request closed without merging**
